Homework 3, Attempt 1 correct branching
EvgeniiKlimenko/EvgeniiKlimenko pull request #4
Opened 2021-03-16 19:19 UTC by EvgeniiKlimenko

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/DifferentElementsPage.java
> +public class DifferentElementsPage {
Create AbstractPage.
Make this page extends AbstractPage.

Move to AbstractPage page object initialization and WebDriver field

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/IndexPage.java
> +public class IndexPage {
Create AbstractPage.
Make this page extends AbstractPage.

Move to AbstractPage page object initialization and WebDriver field

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/IndexPage.java
> +        myDriver.findElement(By.xpath("//header/div/nav/ul[1]/li[3]")).click();
fix locators

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/IndexPage.java
> +    @FindBy(xpath = ("/html/body/header/div/nav/ul[1]/li[position()<5]/a"))
fix locators

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/IndexPage.java
> +    @FindBy(xpath = ("/html/body/div/div[2]/main/div[2]/div[2]/div[position()<5]/div/span"))
fix locators

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/IndexPage.java
> +    @FindBy(xpath = ("/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[position()<6]/a/span"))
fix locators

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/pages/DifferentElementsPage.java
> +    @FindBy(xpath = ("/html/body/div/div[3]/div/div[1]/div/div[1]/section[1]/div[2]/div/ul/li"))
fix locators

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/ex2/Exercise2Test.java
> +        //7. Select radio button
all WebElement work must be in page object, move to PO

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/ex2/Exercise2Test.java
> +        driver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div/div[2]/label[1]")).click();
all WebElement work must be in page object, move to PO

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/ex2/Exercise2Test.java
> +        driver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div/div[2]/label[3]")).click();
all WebElement work must be in page object, move to PO

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/ex2/Exercise2Test.java
> +        driver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div/div[4]/select/option[4]")).click();
all WebElement work must be in page object, move to PO

2021-03-27 20:16 UTC, HronoSF commented on src/test/java/hw3/ex1/Exercise1Test.java
> +        menuList = new ArrayList<>(5);
to enum

2021-03-27 20:50 UTC, HronoSF commented on pom.xml
> +    <profiles>
move Page objects to main package

2021-03-30 20:36 UTC, HronoSF commented on src/test/java/hw3/AbstractBaseTest.java
> +        try {
you will read properties before each test class. Do you need it?
You should create class in utils folder and use properties from it (via static for example)

2021-03-30 20:36 UTC, HronoSF commented on src/test/java/hw3/ex1/Exercise1Test.java
> +        indexPage.login(props.getProperty("user.roman.login"), props.getProperty("user.roman.password"));
do not trigger each time props.getProperty("user.roman.login") or etc. Code duplcication is bad. Create field in AbstractBaseTest and use it

2021-03-30 20:36 UTC, HronoSF commented on pom.xml
> +    <properties>
where is pages?
![image](https://user-images.githubusercontent.com/44112289/113053246-bdd42280-91b0-11eb-8397-7ad63c984aa0.png)

2021-04-14 06:36 UTC, komyagin requested changes

2021-04-14 06:36 UTC, komyagin commented on pom.xml
> +            <version>4.0.0-beta-1</version>
Version should be moved to properties

2021-04-14 06:36 UTC, komyagin commented on pom.xml
> +            <version>4.0.0-beta-1</version>
Version should be moved to properties

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/DifferentElementsPage.java
> +    }
Three methods with the same function should use parameters. One method - one action (read about SOLID principles)

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +    @FindBy(xpath = ("//*[@class='uui-navigation nav navbar-nav m-l8']/li[position()<5]/a"))
Are you sure that is the best locator?

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +    @FindBy(xpath = ("//*[@class='sidebar-menu']/li[position()<6]/a/span"))
Are you sure that is the best locator?

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        myDriver.findElements(By.className("dropdown-toggle")).get(1).click();
You should move By.className("dropdown-toggle") to a variable. Are you sure that get(1) is the only possibility to get element?

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        WebElement userName = myDriver.findElement(By.id("user-name"));
You should move By.id("user-name") to a variable

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        return myDriver.findElement(By.id(frameName));
You should move By.id(frameName) to a variable

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        return myDriver.findElement(By.xpath("/html/body/span/div/div/input"));
It's a bad practice to use an absolute path, only if you don't have another option. And you should move By.xpath to a variable

2021-04-14 06:36 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        headerListTop.findElement(By.xpath("//li[3]/ul/li[8]/a")).click();
Move locators to variables. And maybe we can move WebElement to the top? Is it necessary to declare WebElement here? Are you that these locators are the best?

2021-04-14 06:36 UTC, komyagin commented on src/main/java/utils/PropertiesHolder.java
> +            PROPS.load(new FileInputStream("src/test/resources/userData.properties"));
Declare a constant for the path

2021-04-14 06:36 UTC, komyagin commented on src/test/java/hw3/AbstractBaseTest.java
> +        WebDriverManager.chromedriver().browserVersion("89.0.4389.82").setup();
If you use WebDriverManager why you set the driver version? Is it necessary? If so move the version to constant. But you use PropertiesHolder why don't you use it for version loading?

2021-04-14 06:36 UTC, komyagin commented on src/test/java/hw3/ex1/Exercise1Test.java
> +        Assert.assertEquals(indexPage.getHeaderHorizList().size(), 4);
Don't you magic numbers in assertions. It's good practice to declare constant for this.

2021-04-14 06:36 UTC, komyagin commented on src/test/java/hw3/ex1/Exercise1Test.java
> +        Assert.assertEquals(indexPage.getBenefitImagesList().size(), 4);
Don't you magic numbers in assertions. It's good practice to declare constant for this.

2021-04-14 06:36 UTC, komyagin commented on src/test/java/hw3/ex1/Exercise1Test.java
> +        Assert.assertEquals(sidebarList.size(), 5);
Don't you magic numbers in assertions. It's good practice to declare constant for this.

2021-04-19 18:07 UTC, komyagin approved these changes
HW#3 is accepted

2021-04-20 06:46 UTC, merged