Homework_4, attempt 1
EvgeniiKlimenko/EvgeniiKlimenko pull request #6
Opened 2021-03-30 05:49 UTC by EvgeniiKlimenko

2021-03-30 20:43 UTC, HronoSF commented on src/main/java/pages/DifferentElementsPage.java
> +public class DifferentElementsPage extends AbstractPage {
page objects must be in main

2021-03-30 20:43 UTC, HronoSF commented on src/main/java/pages/DifferentElementsPage.java
> +        PageFactory.initElements(driver, this);
PageFactory.initElements(driver, this); is duplicates should be moved to AbstractPage

2021-03-30 20:43 UTC, HronoSF commented on src/main/java/pages/DifferentElementsPage.java
> +    public void selectCheckBoxes() {
I want that method to be:
public void selectCheckBoxes(List<String> checkboxNames)

you should use String.format() + driver.get(..)

2021-03-30 20:43 UTC, HronoSF commented on src/main/java/pages/DifferentElementsPage.java
> +    public void selectRadioButton() {
I want that method to be:
public void selectRadioBox(String radioBoxName)

you should use String.format() + driver.get(..)

2021-03-30 20:43 UTC, HronoSF commented on src/main/java/pages/DifferentElementsPage.java
> +    public void selectFromDropdownMenu() {
I want that method to be:
public void selectFromDropdownMenu(String option)

you should use String.format() + driver.get(..)

2021-03-30 20:43 UTC, HronoSF commented on src/main/java/pages/IndexPage.java
> +        myDriver.findElement(By.xpath("//header/div/nav/ul[1]/li[3]")).click();
very bad locators, try something else!

2021-03-30 20:43 UTC, HronoSF commented on src/test/java/hw3/AbstractBaseTest.java
> +        props = new Properties();
Same as for hw3. It would be reinitialized after each test class. Create util folder and class to work with properties

2021-03-30 20:43 UTC, HronoSF commented on src/test/java/hw3/ex1/Exercise1Test.java
> +        indexPage.login(props.getProperty("user.roman.login"), props.getProperty("user.roman.password"));
same as for hw3 props.getProperty("user.roman.login") and etc. is duplicates, create constant and use it

2021-03-30 20:43 UTC, HronoSF commented on src/test/java/hw3/ex2/Exercise2Test.java
> +    public void exerciseTwoTest() {
same comment as for ex1

2021-04-14 06:52 UTC, komyagin requested changes

2021-04-14 06:52 UTC, komyagin commented on pom.xml
> +            <scope>compile</scope>
You declare versions in the properties section why don't you use it here?

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/DifferentElementsPage.java
> +        PageFactory.initElements(driver, this);
You should change it according to @HronoSF comment

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/DifferentElementsPage.java
> +    public void selectCheckBoxes() {
You should change it according to @HronoSF comment. I suggest it in previous homework

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        myDriver.findElements(By.className("dropdown-toggle")).get(1).click();
You should move By.className to a variable

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        WebElement userName = myDriver.findElement(By.id("user-name"));
You should move By.id to a variable

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        return myDriver.findElement(By.id(frameName));
You should move By.classId to a variable

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +        return myDriver.findElement(By.xpath("/html/body/span/div/div/input"));
You should move By.xpath to a variable. It's a bad practice to use absolute path, try to change it

2021-04-14 06:52 UTC, komyagin commented on src/main/java/pages/IndexPage.java
> +    }
You should move By.xpath to variables. Bad locators try to change it

2021-04-14 06:52 UTC, komyagin commented on src/main/java/utils/PropertiesHolder.java
> +            PROPS.load(new FileInputStream("src/test/resources/userData.properties"));
You should use a constant for the path

2021-04-14 06:52 UTC, komyagin commented on src/test/java/hw4/AbstractBaseTest.java
> +        WebDriverManager.chromedriver().browserVersion("89.0.4389.90").setup();
You use WebDriverManager why do you declare browser version? If it really necessary you should move the version of the browser to the property file and declare a variable

2021-04-14 06:52 UTC, komyagin commented on src/test/java/hw4/AbstractBaseTest.java
> +        assertionStep = new AssertionStep(driver);
Controversial decision

2021-04-14 06:52 UTC, komyagin commented on src/test/java/hw4/ex1/Exercise1Test.java
> +        assertionStep.pageTitleIsCorrect(driver.getTitle(), "Home Page");
Can we use constant for "Home Page"?

2021-04-14 06:52 UTC, komyagin commented on src/test/java/hw4/ex1/Exercise1Test.java
> +        actionStep.goToIFrameWithName("frame");
Can we use a constant for "frame"?

2021-04-14 06:52 UTC, komyagin commented on src/test/java/hw4/ex2/Exercise2Test.java
> +        assertionStep.pageTitleIsCorrect(driver.getTitle(), "Home Page");
Can we use a constant for "Home page"?

2021-04-14 06:52 UTC, komyagin commented on src/test/java/hw4/ex2/Exercise2Test.java
> +        assertionStep.pageTitleIsCorrect(driver.getTitle(), "Different Elements");
Can we use a constant here?

2021-04-30 11:02 UTC, komyagin approved these changes

2021-05-02 12:55 UTC, merged